#!/usr/bin/env bash
# Scan public/brushes and public/heroes and write src/assets.generated.ts so the template knows
# which real brush strokes and hero layers exist. Run after dropping files in.
set -euo pipefail
cd "$(dirname "$0")/.."
{
  echo "// generated by scripts/sync-assets.sh"
  echo -n "export const BRUSHES: string[] = ["
  ls public/brushes 2>/dev/null | grep -Ei '\.(png|webp)$' | sed 's/.*/"brushes\/&"/' | paste -sd, - || true
  echo "];"
  echo -n "export const HEROES: string[] = ["
  ls public/heroes 2>/dev/null | grep -Ei '\.(png|webp|jpg)$' | sed 's/.*/"heroes\/&"/' | paste -sd, - || true
  echo "];"
} > src/assets.generated.ts
cat src/assets.generated.ts
