// generated by scripts/sync-assets.sh
export const BRUSHES: string[] = ["brushes/brush-01.png","brushes/brush-02.png","brushes/brush-05.png","brushes/brush-06.png"
];
export const HEROES: string[] = ["heroes/07-bg.png","heroes/07-fg.png","heroes/08-bg.png","heroes/08-fg.png","heroes/09-bg.png","heroes/09-fg.png","heroes/14-bg.png","heroes/14-fg.png"
];
